version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    container_name: data_saver

networks:
  default:

volumes:
  redis_data: